export const EVENTS = {
  initGame: "initGame",
  joinGame: "joinGame",
  playerJoined: "playerJoined",
  startGame: "startGame",
  gameStarted: "gameStarted",
  answerQuestion: "answerQuestion",
  playerAnswered: "playerAnswered",
  requestQuestionForVoting: "requestQuestionForVoting",
  questionForVotiong: "questionForVotiong",
  voteForAnswer: "voteForAnswer",
  sendVotes: "sendVotes",
  pointsCalculated: "pointsCalculated",
  calcVotes: "calcVotes",
};
